// <auto-generated />
using System;
using ContactManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactManager.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ContactManager.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Family"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Friend"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Partner"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Coworker"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("ContactManager.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            CategoryId = 1,
                            DateAdded = new DateTime(2022, 5, 5, 21, 34, 16, 306, DateTimeKind.Local).AddTicks(8294),
                            Email = "caty.dogger@yahoo.com",
                            Firstname = "Caty",
                            Lastname = "Dogger",
                            Organization = "Organization 200",
                            PhoneNumber = "000-123-4567"
                        },
                        new
                        {
                            ContactId = 2,
                            CategoryId = 2,
                            DateAdded = new DateTime(2022, 5, 5, 21, 34, 16, 306, DateTimeKind.Local).AddTicks(8323),
                            Email = "fishy.tanks@gmail.com",
                            Firstname = "Fishy",
                            Lastname = "Tanks",
                            Organization = "Org A",
                            PhoneNumber = "000-222-4567"
                        },
                        new
                        {
                            ContactId = 3,
                            CategoryId = 3,
                            DateAdded = new DateTime(2022, 5, 5, 21, 34, 16, 306, DateTimeKind.Local).AddTicks(8326),
                            Email = "hamlet.burgers@hotmail.com",
                            Firstname = "Hamlet",
                            Lastname = "Burgers",
                            Organization = "Org B",
                            PhoneNumber = "000-444-4567"
                        },
                        new
                        {
                            ContactId = 4,
                            CategoryId = 4,
                            DateAdded = new DateTime(2022, 5, 5, 21, 34, 16, 306, DateTimeKind.Local).AddTicks(8328),
                            Email = "kermittacus.froggius@rocketmail.com",
                            Firstname = "Kermittacus",
                            Lastname = "Froggius",
                            Organization = "Muppets Inc.",
                            PhoneNumber = "000-555-4567"
                        },
                        new
                        {
                            ContactId = 5,
                            CategoryId = 5,
                            DateAdded = new DateTime(2022, 5, 5, 21, 34, 16, 306, DateTimeKind.Local).AddTicks(8330),
                            Email = "chocobo.latte@aol.com",
                            Firstname = "Chocobo",
                            Lastname = "Latte",
                            Organization = "Org C",
                            PhoneNumber = "000-888-4567"
                        });
                });

            modelBuilder.Entity("ContactManager.Models.Contact", b =>
                {
                    b.HasOne("ContactManager.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
